version: '3.1'

services:
  package-base:
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      POLARIS_TEST_DB_URL: postgres://polaris:polaris@polaris-db/polaris_test
    depends_on:
      - polaris-db

  package:
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      POLARIS_TEST_DB_URL: postgres://polaris:polaris@polaris-db/polaris_test
    depends_on:
      - polaris-db









