version: '3.1'

services:
  package-base:
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      POLARIS_TEST_DB_URL: postgresql://polaris:polaris@polaris-db/polaris_test
    depends_on:
      - polaris-db

  package:
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      POLARIS_TEST_DB_URL: postgresql://polaris:polaris@polaris-db/polaris_test
    depends_on:
      - polaris-db

  polaris-vcs-service:
    image: ${PACKAGE_DEPLOYABLE_IMAGE}
    build:
      dockerfile: docker/polaris-vcs-service-deploy/Dockerfile
      context: .
      args:
        PACKAGE_UWSGI_IMAGE: ${PACKAGE_UWSGI_IMAGE}
    ports:
      - "8100:8100"







